### ISSUE TITLE
Perform database setup

### ISSUE THREAD

**Issue by brendanator** [brendanator/postevent#34]
Create a class for instantiating the database:

- Create the schema postevent if it doesn't exist
- Create a table (if it doesn't exist) `postevent.<topic>` where `<topic>` is a parameter. The table should contain the following columns
```
                    idn bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                    id VARCHAR(255) NOT NULL,
                    source VARCHAR(1024) NOT NULL,
                    type VARCHAR(255) NOT NULL,
                    datacontenttype VARCHAR(255),
                    dataschema VARCHAR(255),
                    subject VARCHAR(255),
                    data bytea,
                    time TIMESTAMP WITH TIME ZONE default current_timestamp,
                    UNIQUE (id, source)
```

**Comment by brendanator** [comment]
@sourcery-ai plan

**Comment by brendanator** [comment]
@sourcery-ai develop

**Comment by brendanator** [comment]
@sourcery-ai plan

**Comment by brendanator** [comment]
@sourcery-ai plan

**Comment by brendanator** [comment]
@sourcery-ai plan

**Comment by brendanator** [comment]
@sourcery-ai develop

**Comment by brendanator** [comment]
@sourcery-ai plan

**Comment by ghost** [comment]
## Objectives
- Create a new database setup class to manage PostgreSQL schema and table creation
- Implement method to create `postevent` schema if it doesn't exist
- Implement method to create parameterized table `postevent.<topic>` with specified columns and constraints
- Add error handling for database operations
- Ensure idempotent execution of schema and table creation
- Add unique constraint on `id` and `source` columns
- Configure identity column `idn` as primary key with auto-increment
- Set up timestamp column with default current time zone value

## Setup commands


## File changes
`src/main/java/com/p14n/postevent/DatabaseSetup.java`

- Create new `DatabaseSetup` class to manage database initialization
- Add constructor that takes JDBC connection parameters
- Add method `createSchemaIfNotExists()` to create the `postevent` schema
- Add method `createTableIfNotExists(String topic)` to create the table with specified columns
- Add error handling and logging for database operations

`src/test/java/com/p14n/postevent/DatabaseSetupTest.java`

- Create test class for `DatabaseSetup`
- Add test for schema creation
- Add test for table creation with different topic names
- Add test to verify all column definitions and constraints
- Add test to verify idempotent execution

## Verify commands
- `./gradlew test` - ❌

---

This plan was automatically generated.
Please review the plan carefully and make any necessary adjustments.

**Comment by brendanator** [comment]
@sourcery-ai develop

**Comment by brendanator** [comment]
@sourcery-ai develop
