### ISSUE TITLE
Add hello world class

### ISSUE THREAD

**Issue by brendanator** [brendanator/postevent#8]
- create a hello world class that creates the string "Hello world", with a main method that prints to std out
- add a gradle task to run the hello world class

**Comment by brendanator** [comment]
@sourcery-ai plan

**Comment by ghost** [comment]
## Objectives
- Create a Java class with a main method that outputs 'Hello world'
- Configure Gradle build file to include the new class in the source set
- Create a new Gradle task to execute the Hello World program
- Ensure the Gradle task is properly linked to the main class

## File changes
`src/main/java/com/p14n/postevent/HelloWorld.java`

- Create new `HelloWorld` class in the `com.p14n.postevent` package
- Add `main` method that prints 'Hello world' to standard output

`build.gradle`

- Add new Gradle task called `runHelloWorld` that executes the HelloWorld class
- Configure the task to use `com.p14n.postevent.HelloWorld` as the main class

---

This plan was automatically generated.
Please review the plan carefully and make any necessary adjustments.

**Comment by brendanator** [comment]
@sourcery-ai develop
